### PR TITLE
constrain package to remove conflict with python-javabridge

### PR DESCRIPTION
**Pull request by raivivek**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by raivivek** [comment]
@jakirkham Looks like I don't have the access to merge this.

**Comment by raivivek** [comment]
@conda-forge-admin, please re-render.

**Comment by raivivek** [comment]
@conda-forge/staged-recipes Could we merge this please? Thank you!

**Pull request merged**
